[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
user_profile_backend = "EEoe57rfT1qw8SrCy1M1AmVQUJjXndFRY4q5KYWwGdj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"